const types = [
    {
        id: "1",
        title: "Fit In 50st, 60st, 70st",
        url: "https://fitnesstogether.com/files/frontend/cropped/ftbanner11.jpg",
        text: "Ne postoje godine  u kojima je kontraindikovano vežbanje. Samo je potrebno vežbu i trening prilagoditi godinama i zdravstvenom statusu. Zato je potrebno da imate svog trenera i da trening bude isplaniran i sproveden tako da što duže održi vitalnost vašeg organizma, njegovu funkcionalnost i dobro fizičko stanje. Uz prave vežbe i odgovarajući  trening možete zaustaviti proces starenja i poboljšati svoje zdravlje.",
        footTxt: "Dođite da vežbamo zajedno!"
    },
    {
        id: "2",
        title: "Power Plate",
        url: "https://previews.123rf.com/images/dolgachov/dolgachov1501/dolgachov150100840/35027127-fitness-sport-training-gym-and-lifestyle-concept-group-of-women-working-out-with-steppers-in-gym.jpg",
        text: "Kada jednom osetiš moć grupnog fitnesa, on postaje deo tvoje svakodnevnice. A to je dobra stvar! Treninzi su prilagođeni svima i svaki ima drugačiji koncept. Izaberi onaj koji ti najviše odgovara i uživaj u promenama!Sam trening na spravi traje oko 20 minuta, što znatno štedi vreme treniranja, nakon čega sledi istezanje i masaža na samoj spravi.Power Plate je izuzetno efikasan, a rezultati su vidljivi za veoma kratko vreme.",
        trng_h2: "Vežbanjem na Power Plate-u se postiže:",
        li1: "kompletan trening snage u trajanju od 20 minuta",
        li2: "poboljšanja snage i tonusa mišića",
        li3: "ubrzavanje metabolizma i smanjenje telesne težine",
        li4: "pomaže u borbi protiv celulita i u proizvodnji kolagena",
        li5: "povećava snagu",
        li6: "poboljšava ravnotežu i elastičnost",
        li7: "opušta i umanjuje stres podstičući lučenje hormona sreće",
        li8: "pomaže u borbi protiv osteoporoze i povećava gustinu mišićne mase",
        li9: "smanjuje rizik od povreda i ubrzava oporavak",
        footTxt: "Vaše je samo da zakažete trening i isprobate ovu čudesnu spravu, a mi ćemo vam pomoći da iz treninga izvučete maksimum. ",
    },
    {
        id: "3",
        title: "Funkcionali trening",
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR9HNBRT1jXTx0AvFpIjgC5kkUWTKOVpQb1DEsPMtL8ksHupJHC",
        text: "Funkcionalni trening predstavlja korišćenje osnovnih pokreta i vežbi koje su izvedene iz prirodnog kretanja. Njegov osnovni cilj je da nas pripremi za osnovne, svakodnevne aktivnosti.On se može definisati kao pokret ili vežba, čije su osnove izvedene iz prirodnog kretanja. Kako bi trening bio funkcionalan potrebno je korišćenje funkcionalnih rekvizita – sredstava koja će omogućiti našem telu da se kreće bez ograničenja.",
        trng_h2: "Ovakvim treningom možemo da postignemo:",
        li1: "Povećanje mišićne mase, snage, izdržljivosti i brzine",
        li2: "Poboljšanje elastičnosti i fleksibilnosti",
        li3: "Jačanje kardio-vaskularnog sistema",
        li4: "Ubrzavanje metabolizma",
        li5: "Gubitak masnih naslaga",
        li6: "Prevencija povreda",
        li7: "Pomoć u rehabilitaciji",
        li8: "Poboljšanje pravilnog držanja tela…",
    },
    {
        id: "4",
        title: "Fit fast program",
        url: "https://cnet3.cbsistatic.com/img/zAME7LNqsjGHz2122mOaBckd844=/2019/11/09/e3b5e6da-5d8d-4651-88ec-9e1979ef9535/gettyimages-1034882426.jpg",
        text: "Fit fast je tromesečni program kojim ćete dobiti sve što vam je potrebno za brzu i uspešnu transformaciju tela, treninge i plan ishrane. Ovaj program je namenjen svima onima koji bi hteli da na brz, efikasan i zdrav način dođu do željene težine.Nakon ovog programa možete očekivati znatno smanjenje telesne mase i procenta masnog tkiva, povećanje mišićne mase, više energije, bolje držanje i oblikovano, zategnuto telo.",
        trng_h2: "Program obuhvata:",
        li1: "Početnu proveru, testiranje",
        li2: "Individualni program treninga 3-5 puta nedeljno",
        li3: "Individualan plan ishrane",
        li4: "Kontrole i merenja na svakih 15 dana",
        li5: "Zajedničke radionice svih polaznika ovog programa",
        li6: "Svakodnevna online podrska",
    },

];

export default types;